### ISSUE TITLE
Rewrite 12, Hotfix 4, Bug compilation

### ISSUE THREAD

**Issue by Zion131313** [DegenDomain/LolilithsThroneIssueTracker#5]
**Details**
- Companion issue is **not** fixed, persists with the exact same error in the log as in the other bug report for this issue.
- Slaver license quest issue is not fixed, persists with no error.
- Demons everywhere %chance and major perk # settings reset after closing and opening the game, no error.

**Comment by DrakeFaewylde** [comment]
Companion issue - Are you using a new save? Old saves will stay bugged.
Slaver License - I'm looking into this now.
New Mod Options not saving - I'll fix this today.

**Comment by Zion131313** [comment]
New save, I make a new save with every single update and hotfix.

**Comment by DrakeFaewylde** [comment]
New Mod Options - Fixed for next hotfix.
Slaver License - Definitely fixed it this time.
Companion Issue - Are you certain it's the same error? There's a nullcheck included, so I need to be absolutely certain it's actually the same error. Can you provide an error log?

**Comment by DrZed** [comment]
Validate these issues are fixed from the usual download location my website beta.php then we close this issue

**Comment by Zion131313** [comment]
Rewrite 13, Companion issue persists, error log attached.
[error.log](https://github.com/DegenDomain/LolilithsThroneIssueTracker/files/11831028/error.log)

**Comment by DrZed** [comment]
The issue is due to the way loading works, everything is null as the game loads and procedurally populates the data as the game also tries to also continue checking everything constantly. So it's not always going to be null I believe, just in earlier stages.

Quite similarly to an issue I ran into and had to patch for something else, where the game would throw a ton of null errors during new game or loading saves for a bunch of other shit in the game, because as the game is loading that stuff tries to call before the data has actually loaded. Innoxia hid all of that shitty code behind Try { function(); } catch (Exception ignored) {} (she doesn't spit the errors just ignores them)

I went and fixed the issues myself this time. Let me know if something significant happens related to your word of caution.

**Comment by DrZed** [comment]
One such exact instance is Slave loading code, the slaves aren't loaded until later so trying to add them to the player before the slaves have loaded caused me quite the headache. Or calling functions for setting body parts during init prior to the body being initialized, or even the inverse of the first instance, of a slave being loaded before their master (npc) being loaded. Innoxia just ignored all those issues in the code just wrapped in a (Do this and don't crash if anything goes wrong) way of handling. I went through and ripped out most of those Try/Catches to solve the underlying issues rather than letting the game spew errors into the void.

**Comment by DrZed** [comment]
Patch released on my site, sorry for the inconvenience and head banging.

**Comment by Zion131313** [comment]
Rewrite 14
Loading issue resolved, however companions are still impossible to remove from party (neither the "send home" nor "remove from party" buttons do anything).
Attached are two error logs, one from before closing and reopening the game, the other after, in that order, though I doubt they're relevant to this issue.
[error.log](https://github.com/DegenDomain/LolilithsThroneIssueTracker/files/11833438/error.log)
[error.log](https://github.com/DegenDomain/LolilithsThroneIssueTracker/files/11833440/error.log)

**Comment by DrZed** [comment]
[Fatal Error] vagina.xml:1:14: A pseudo attribute name is expected.
[Fatal Error] vagina.xml:1:14: White space is required between the processing instruction target and data.
[Fatal Error] face.xml:19:3: Element type "null" must be followed by either attribute specifications, ">" or "/>".
These fatal errors are fatal in name only as they just happen rarely in startup of the game. I am thinking of adding timestamps to the logs, I'll be passing that new-ish issue to @DrakeFaewylde as I'm not rested and will be sleeping soon.

**Comment by DrakeFaewylde** [comment]
I took a slightly different approach and in my tests the issue seems to be resolved.

R14 Hotfix 1 released. Please test and confirm the issue is resolved.

**Comment by Zion131313** [comment]
Tested, the issue is resolved.
Thank you.
